name: Mirror and push

on: 
  workflow_dispatch:
  schedule:
    - cron:  '45 11 * * 3'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout actions
      uses: actions/checkout@v1

    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
     
    - name: Install requests
      run: pip install requests
 
    - name: Download
      run: |
        python download.py
      
    - name: Releases mirror
      uses: ncipollo/release-action@v1
      with:
        artifacts: "output/scratch-win.exe,output/scratch-mac.dmg"
        token: ${{ secrets.PUBLISH }}
        body: |
          { "describe_zh" : "这些文件属于 scratch.mit.edu/download 而不属于 ASDM，ASDM 所做的只是镜像这些文件。",
            "describe_en" : "( These files are from scratch.mit.edu/download and not belongs to asdm, asdm to do are just mirror these files. )",
            "scratch_version": "${{ env.scratch_version }}" }
        
        tag: ${{ github.run_id }}
